<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <!-- Roslyn генераторы ДОЛЖНЫ быть на netstandard2.0 -->
        <TargetFramework>netstandard2.0</TargetFramework>
        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
        <IsRoslynComponent>true</IsRoslynComponent>
        <!-- Включаем современный C# (9.0+), чтобы работал синтаксис "new()" -->
        <LangVersion>9.0</LangVersion>
        <!-- Включаем поддержку ValueTuple и современных типов для старого netstandard -->
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <!-- Пакеты Roslyn. Версия 4.3.0 идеально совместима со встроенным в Unity компилятором -->
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.3.0" PrivateAssets="all" />
        <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.3" PrivateAssets="all" />

        <!-- Фикс для ошибки "Type System.ValueTuple is not resolved" -->
        <PackageReference Include="System.ValueTuple" Version="4.5.0" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Properties\" />
    </ItemGroup>
</Project>
