using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Doject;

[Generator]
public class SystemLookupInjectorGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new SystemSyntaxReceiver());
    }

    public void Execute(GeneratorExecutionContext context)
    {
        if (!(context.SyntaxContextReceiver is SystemSyntaxReceiver receiver)) return;

        foreach (var systemSyntax in receiver.CandidateSystems)
        {
            var model = context.Compilation.GetSemanticModel(systemSyntax.SyntaxTree);
            if (!(model.GetDeclaredSymbol(systemSyntax) is INamedTypeSymbol systemSymbol)) continue;

            bool hasInjectSystemAttr = systemSymbol.GetAttributes().Any(attr =>
            {
                var name = attr.AttributeClass?.Name;
                return name == "AutoInjectSystem" || name == "AutoInjectSystemAttribute";
            });

            if (!hasInjectSystemAttr) continue;

            string systemName = systemSymbol.Name;

            var nestedJobs = new List<INamedTypeSymbol>();
            foreach (var member in systemSymbol.GetTypeMembers())
            {
                bool isJob = member.GetAttributes().Any(attr =>
                {
                    var name = attr.AttributeClass?.Name;
                    return name == "AutoInject" || name == "AutoInjectAttribute" ||
                           name == "AutoInjectLookups" || name == "AutoInjectLookupsAttribute";
                });

                if (isJob)
                {
                    nestedJobs.Add(member);
                }
            }

            if (nestedJobs.Count == 0) continue;

            var cacheFieldsSb = new StringBuilder();
            var initCacheSb = new StringBuilder();
            var updateCacheSb = new StringBuilder();

            foreach (var jobSymbol in nestedJobs)
            {
                string jobName = jobSymbol.Name;
                string fieldName = "_" + char.ToLowerInvariant(jobName[0]) + jobName.Substring(1) + "Cache";

                cacheFieldsSb.AppendLine($"    private {jobName}.Cache {fieldName};");
                initCacheSb.AppendLine($"        {fieldName}.Init(ref state);");
                updateCacheSb.AppendLine($"        {fieldName}.Update(ref state);");
            }

            bool hasNamespace = !systemSymbol.ContainingNamespace.IsGlobalNamespace;
            string ns = hasNamespace ? systemSymbol.ContainingNamespace.ToDisplayString() : "";

            var nsOpen = hasNamespace ? $"namespace {ns}\n{{\n" : "";
            var nsClose = hasNamespace ? "}\n" : "";
            string indent = hasNamespace ? "    " : "";

            string safeFileName = systemSymbol.ToDisplayString()
                .Replace("global::", "")
                .Replace("<", "_")
                .Replace(">", "_")
                .Replace(".", "_");

            var source = $@"// <auto-generated />
using Unity.Entities;

{nsOpen}{indent}public partial struct {systemName}
{indent}{{
{cacheFieldsSb.ToString().TrimEnd()}

{indent}    partial void OnSystemCreate(ref SystemState state);
{indent}    partial void OnSystemUpdate(ref SystemState state);

{indent}    public void OnCreate(ref SystemState state)
{indent}    {{
{initCacheSb.ToString().TrimEnd()}
{indent}        OnSystemCreate(ref state);
{indent}    }}

{indent}    public void OnUpdate(ref SystemState state)
{indent}    {{
{updateCacheSb.ToString().TrimEnd()}
{indent}        OnSystemUpdate(ref state);
{indent}    }}
{indent}}}
{nsClose}";

            context.AddSource($"{safeFileName}_SystemInject.g.cs", SourceText.From(source, Encoding.UTF8));
        }
    }

    private class SystemSyntaxReceiver : ISyntaxContextReceiver
    {
        public List<StructDeclarationSyntax> CandidateSystems { get; } = new();

        public void OnVisitSyntaxNode(GeneratorSyntaxContext context)
        {
            if (context.Node is StructDeclarationSyntax structDecl && structDecl.AttributeLists.Count > 0)
            {
                CandidateSystems.Add(structDecl);
            }
        }
    }
}